/**
 * Builds the area and service pages.
 *
 *   npm run build:pages
 *
 * Vercel runs no build step: `public/` is served exactly as it is on disk. So
 * this is an authoring tool, not a deploy step, and its output is committed.
 * The alternative, hand writing twenty near-identical documents, is how they
 * drift apart.
 *
 * Output lives under public/areas/<site>/<slug>.html and is served at
 * /damp-survey/<slug> on the right host by middleware.js. The two sites need
 * separate directories because one Vercel project serves both domains, so the
 * same public path would otherwise collide.
 */
import { mkdir, writeFile, readFile, readdir, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { areas } from '../content/areas/index.js';
import { services } from '../content/services/index.js';
import { render, distinctiveWordCount, SITES } from './area-template.js';
import { render as renderService, distinctiveWordCount as serviceWords } from './service-template.js';
import { reviewsBlock, reviewsSummary, START as R_START, END as R_END } from './reviews-block.js';
import { render as renderHub } from './hub-template.js';
import { render as renderPricing } from './pricing-template.js';
import { assetHashes, stampAssets } from './asset-version.js';
import { bookForm } from './book-form.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'public', 'areas');
const SERVICES_OUT = join(ROOT, 'public', 'service-pages');
const HUBS_OUT = join(ROOT, 'public', 'hubs');

/* A page whose only local content is its name is a doorway page. Google demotes
   those, and it would take the rest of the site down with it, so the build
   fails rather than shipping one. */
const MIN_WORDS = 250;

function check(area, seen) {
  const problems = [];
  const required = ['slug', 'site', 'name', 'title', 'h1', 'intro', 'coverage'];
  for (const field of required) {
    if (!area[field]) problems.push(`missing ${field}`);
  }
  for (const field of ['stock', 'common', 'places', 'districts', 'faq']) {
    if (!Array.isArray(area[field]) || !area[field].length) problems.push(`${field} is empty`);
  }
  if (!SITES[area.site]) problems.push(`unknown site "${area.site}"`);
  if (area.slug && !/^[a-z0-9-]+$/.test(area.slug)) problems.push('slug must be lower case and hyphenated');

  const key = `${area.site}/${area.slug}`;
  if (seen.has(key)) problems.push('duplicate slug for this site');
  seen.add(key);

  if (!problems.length) {
    const count = distinctiveWordCount(area);
    if (count < MIN_WORDS) {
      problems.push(`only ${count} words of content specific to this area, needs ${MIN_WORDS}`);
    }
  }
  return problems;
}

/* The sitemaps are generated here too, so adding an area cannot leave a page
   that nothing links to and nothing lists. */
export function sitemapFor(site, today) {
  const origin = SITES[site].origin;
  const urls = [
    { loc: `${origin}/`, priority: '1.0', changefreq: 'monthly' },
    { loc: `${origin}/services`, priority: '0.9', changefreq: 'monthly' },
    { loc: `${origin}/damp-survey`, priority: '0.9', changefreq: 'monthly' },
    ...(site === 'ati' ? [{ loc: `${origin}/pricing`, priority: '0.9', changefreq: 'monthly' }] : []),
    ...services
      .filter((s) => s.site === site)
      .map((s) => ({ loc: `${origin}/services/${s.slug}`, priority: '0.9', changefreq: 'monthly' })),
    ...areas
      .filter((a) => a.site === site)
      .map((a) => ({ loc: `${origin}/damp-survey/${a.slug}`, priority: '0.8', changefreq: 'monthly' }))
  ];
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-areas.js. Edit content/areas, not this file. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`).join('\n')}
</urlset>
`;
}

/* The home pages carry the links into the area pages. A page nothing links to
   is a page Google treats as unimportant, so this is not decoration: it is the
   difference between the area pages being crawled and being ignored. Written
   between markers so adding an area updates both sites automatically. */
const HOME = { dampscan: 'public/index.html', ati: 'public/london.html' };
const START = '<!-- area-links:start, filled by scripts/build-pages.js -->';
const END = '<!-- area-links:end -->';

/* The booking form on the two home pages. It lived there as hand written markup
   and every other page generated its own from scripts/book-form.js, which is two
   copies of one form and they drifted: the home pages reworded their buttons,
   the generated pages did not, and a field added to one was missing from the
   other. Writing it here makes book-form.js the only copy. */
const BF_START = '<!-- book-form:start, filled by scripts/build-pages.js -->';
const BF_END = '<!-- book-form:end -->';

async function writeBookForm() {
  for (const [site, file] of Object.entries(HOME)) {
    const path = join(ROOT, file);
    const html = await readFile(path, 'utf8');
    const from = html.indexOf(BF_START);
    const to = html.indexOf(BF_END);
    if (from === -1 || to === -1) throw new Error(`${file}: book form markers missing`);
    const block = `${BF_START}\n${bookForm(site)}\n    ${BF_END}`;
    await writeFile(path, html.slice(0, from) + block + html.slice(to + BF_END.length), 'utf8');
  }
}

async function writeHomeLinks() {
  for (const [site, file] of Object.entries(HOME)) {
    const path = join(ROOT, file);
    const html = await readFile(path, 'utf8');
    const from = html.indexOf(START);
    const to = html.indexOf(END);
    if (from === -1 || to === -1) throw new Error(`${file}: area link markers missing`);

    const areaLinks = areas
      .filter((a) => a.site === site)
      .map((a) => `        <li><a href="/damp-survey/${a.slug}">Damp surveys in ${a.name}</a></li>`)
      .join('\n');

    const serviceLinks = services
      .filter((s) => s.site === site)
      .map((s) => `        <li><a href="/services/${s.slug}">${s.name}</a></li>`)
      .join('\n');

    const block = `${START}
    <div class="area-links">
      <h3>Area guides</h3>
      <ul>
${areaLinks}
      </ul>
      <h3 style="margin-top:22px">Guides by problem</h3>
      <ul>
${serviceLinks}
      </ul>
    </div>
    ${END}`;

    await writeFile(path, html.slice(0, from) + block + html.slice(to + END.length), 'utf8');
  }
}

/* The reviews we hold, written into the markup rather than fetched, because a
   crawler that does not run JavaScript sees only what is in the HTML. */
async function writeReviews() {
  for (const [site, file] of Object.entries(HOME)) {
    const path = join(ROOT, file);
    const html = await readFile(path, 'utf8');
    const from = html.indexOf(R_START);
    const to = html.indexOf(R_END);
    if (from === -1 || to === -1) throw new Error(`${file}: review markers missing`);
    await writeFile(path, html.slice(0, from) + reviewsBlock(site) + html.slice(to + R_END.length), 'utf8');
  }
}

/* Runs last, over every page the site serves, so that whatever the other
   passes wrote is what gets stamped. /assets is cached immutable for a year,
   and this is what makes that safe: see scripts/asset-version.js. */
async function stampAllPages() {
  const hashes = await assetHashes(ROOT);
  let stamped = 0;
  async function walk(dir) {
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) { if (entry.name !== 'staff') await walk(path); continue; }
      if (!entry.name.endsWith('.html')) continue;
      const html = await readFile(path, 'utf8');
      const out = stampAssets(html, hashes);
      if (out !== html) { await writeFile(path, out, 'utf8'); stamped++; }
    }
  }
  await walk(join(ROOT, 'public'));
  return { files: hashes.size, stamped };
}

async function writeSitemaps() {
  // One date for the whole build, taken once, so a run cannot straddle midnight
  // and stamp two different days across the two files.
  const today = new Date().toISOString().slice(0, 10);
  await writeFile(join(ROOT, 'public', 'sitemap.xml'), sitemapFor('dampscan', today), 'utf8');
  await writeFile(join(ROOT, 'public', 'sitemap-london.xml'), sitemapFor('ati', today), 'utf8');
}

function checkService(service, seen) {
  const problems = [];
  for (const field of ['slug', 'site', 'name', 'title', 'h1', 'intro', 'signsHeading', 'ctaHeading', 'ctaBody']) {
    if (!service[field]) problems.push(`missing ${field}`);
  }
  for (const field of ['signs', 'sections', 'faq']) {
    if (!Array.isArray(service[field]) || !service[field].length) problems.push(`${field} is empty`);
  }
  if (!SITES[service.site]) problems.push(`unknown site "${service.site}"`);

  const key = `${service.site}/${service.slug}`;
  if (seen.has(key)) problems.push('duplicate slug for this site');
  seen.add(key);

  if (!problems.length && serviceWords(service) < MIN_WORDS) {
    problems.push(`only ${serviceWords(service)} words written for this service, needs ${MIN_WORDS}`);
  }
  return problems;
}

async function main() {
  const seen = new Set();
  const failures = [];

  for (const area of areas) {
    const problems = check(area, seen);
    if (problems.length) failures.push(`area ${area.slug || '(no slug)'}: ${problems.join(', ')}`);
  }
  const seenServices = new Set();
  for (const service of services) {
    const problems = checkService(service, seenServices);
    if (problems.length) failures.push(`service ${service.slug || '(no slug)'}: ${problems.join(', ')}`);
  }
  if (failures.length) {
    console.error('Page content is not ready to build:\n  ' + failures.join('\n  '));
    process.exit(1);
  }

  // Clear first, so renaming a slug does not leave the old page live for ever.
  await rm(OUT, { recursive: true, force: true });

  const counts = {};
  for (const area of areas) {
    const dir = join(OUT, area.site);
    await mkdir(dir, { recursive: true });
    await writeFile(join(dir, `${area.slug}.html`), render(area, areas), 'utf8');
    counts[area.site] = (counts[area.site] || 0) + 1;
  }

  await rm(HUBS_OUT, { recursive: true, force: true });
  for (const site of Object.keys(SITES)) {
    const dir = join(HUBS_OUT, site);
    await mkdir(dir, { recursive: true });
    const svc = services.filter((s) => s.site === site);
    const ars = areas.filter((a) => a.site === site);
    await writeFile(join(dir, 'services.html'), renderHub('services', site, svc), 'utf8');
    await writeFile(join(dir, 'areas.html'), renderHub('areas', site, ars), 'utf8');
  }

  // ATi only. DampScan's survey fee is one line inside a larger job, so
  // publishing it alone would misrepresent what a customer actually pays.
  await mkdir(join(ROOT, 'public', 'pricing'), { recursive: true });
  await writeFile(join(ROOT, 'public', 'pricing', 'ati.html'), renderPricing(), 'utf8');

  await rm(SERVICES_OUT, { recursive: true, force: true });
  for (const service of services) {
    const dir = join(SERVICES_OUT, service.site);
    await mkdir(dir, { recursive: true });
    await writeFile(join(dir, `${service.slug}.html`), renderService(service, services), 'utf8');
  }

  await writeSitemaps();
  await writeBookForm();
  await writeHomeLinks();
  await writeReviews();
  const stamps = await stampAllPages();

  for (const site of Object.keys(counts).sort()) {
    const built = await readdir(join(OUT, site));
    console.log(`${site}: ${built.length} pages`);
  }
  console.log(`${areas.length} area pages written to public/areas`);
  console.log(`${services.length} service pages written to public/service-pages`);
  console.log('4 hub pages written to public/hubs');
  console.log('ATi pricing page written to public/pricing');
  console.log('sitemaps, home page links and home page booking forms rewritten');
  console.log(`${stamps.files} assets hashed, ${stamps.stamped} pages restamped`);
  for (const site of Object.keys(HOME)) console.log(reviewsSummary(site));
}

await main();
