/**
 * Builds the area and service pages.
 *
 *   npm run build:pages
 *
 * Vercel runs no build step: `public/` is served exactly as it is on disk. So
 * this is an authoring tool, not a deploy step, and its output is committed.
 * The alternative, hand writing twenty near-identical documents, is how they
 * drift apart.
 *
 * Output lives under public/areas/<site>/<slug>.html and is served at
 * /damp-survey/<slug> on the right host by middleware.js. The two sites need
 * separate directories because one Vercel project serves both domains, so the
 * same public path would otherwise collide.
 */
import { mkdir, writeFile, readFile, readdir, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { areas } from '../content/areas/index.js';
import { services } from '../content/services/index.js';
import { render, distinctiveWordCount, SITES } from './area-template.js';
import { render as renderService, distinctiveWordCount as serviceWords } from './service-template.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'public', 'areas');
const SERVICES_OUT = join(ROOT, 'public', 'service-pages');

/* A page whose only local content is its name is a doorway page. Google demotes
   those, and it would take the rest of the site down with it, so the build
   fails rather than shipping one. */
const MIN_WORDS = 250;

function check(area, seen) {
  const problems = [];
  const required = ['slug', 'site', 'name', 'title', 'h1', 'intro', 'coverage'];
  for (const field of required) {
    if (!area[field]) problems.push(`missing ${field}`);
  }
  for (const field of ['stock', 'common', 'places', 'districts', 'faq']) {
    if (!Array.isArray(area[field]) || !area[field].length) problems.push(`${field} is empty`);
  }
  if (!SITES[area.site]) problems.push(`unknown site "${area.site}"`);
  if (area.slug && !/^[a-z0-9-]+$/.test(area.slug)) problems.push('slug must be lower case and hyphenated');

  const key = `${area.site}/${area.slug}`;
  if (seen.has(key)) problems.push('duplicate slug for this site');
  seen.add(key);

  if (!problems.length) {
    const count = distinctiveWordCount(area);
    if (count < MIN_WORDS) {
      problems.push(`only ${count} words of content specific to this area, needs ${MIN_WORDS}`);
    }
  }
  return problems;
}

/* The sitemaps are generated here too, so adding an area cannot leave a page
   that nothing links to and nothing lists. */
export function sitemapFor(site, today) {
  const origin = SITES[site].origin;
  const urls = [
    { loc: `${origin}/`, priority: '1.0', changefreq: 'monthly' },
    ...services
      .filter((s) => s.site === site)
      .map((s) => ({ loc: `${origin}/services/${s.slug}`, priority: '0.9', changefreq: 'monthly' })),
    ...areas
      .filter((a) => a.site === site)
      .map((a) => ({ loc: `${origin}/damp-survey/${a.slug}`, priority: '0.8', changefreq: 'monthly' }))
  ];
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-areas.js. Edit content/areas, not this file. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`).join('\n')}
</urlset>
`;
}

/* The home pages carry the links into the area pages. A page nothing links to
   is a page Google treats as unimportant, so this is not decoration: it is the
   difference between the area pages being crawled and being ignored. Written
   between markers so adding an area updates both sites automatically. */
const HOME = { dampscan: 'public/index.html', ati: 'public/london.html' };
const START = '<!-- area-links:start, filled by scripts/build-pages.js -->';
const END = '<!-- area-links:end -->';

async function writeHomeLinks() {
  for (const [site, file] of Object.entries(HOME)) {
    const path = join(ROOT, file);
    const html = await readFile(path, 'utf8');
    const from = html.indexOf(START);
    const to = html.indexOf(END);
    if (from === -1 || to === -1) throw new Error(`${file}: area link markers missing`);

    const areaLinks = areas
      .filter((a) => a.site === site)
      .map((a) => `        <li><a href="/damp-survey/${a.slug}">Damp surveys in ${a.name}</a></li>`)
      .join('\n');

    const serviceLinks = services
      .filter((s) => s.site === site)
      .map((s) => `        <li><a href="/services/${s.slug}">${s.name}</a></li>`)
      .join('\n');

    const block = `${START}
    <div class="area-links">
      <h3>Area guides</h3>
      <ul>
${areaLinks}
      </ul>
      <h3 style="margin-top:22px">Guides by problem</h3>
      <ul>
${serviceLinks}
      </ul>
    </div>
    ${END}`;

    await writeFile(path, html.slice(0, from) + block + html.slice(to + END.length), 'utf8');
  }
}

async function writeSitemaps() {
  // One date for the whole build, taken once, so a run cannot straddle midnight
  // and stamp two different days across the two files.
  const today = new Date().toISOString().slice(0, 10);
  await writeFile(join(ROOT, 'public', 'sitemap.xml'), sitemapFor('dampscan', today), 'utf8');
  await writeFile(join(ROOT, 'public', 'sitemap-london.xml'), sitemapFor('ati', today), 'utf8');
}

function checkService(service, seen) {
  const problems = [];
  for (const field of ['slug', 'site', 'name', 'title', 'h1', 'intro', 'signsHeading', 'ctaHeading', 'ctaBody']) {
    if (!service[field]) problems.push(`missing ${field}`);
  }
  for (const field of ['signs', 'sections', 'faq']) {
    if (!Array.isArray(service[field]) || !service[field].length) problems.push(`${field} is empty`);
  }
  if (!SITES[service.site]) problems.push(`unknown site "${service.site}"`);

  const key = `${service.site}/${service.slug}`;
  if (seen.has(key)) problems.push('duplicate slug for this site');
  seen.add(key);

  if (!problems.length && serviceWords(service) < MIN_WORDS) {
    problems.push(`only ${serviceWords(service)} words written for this service, needs ${MIN_WORDS}`);
  }
  return problems;
}

async function main() {
  const seen = new Set();
  const failures = [];

  for (const area of areas) {
    const problems = check(area, seen);
    if (problems.length) failures.push(`area ${area.slug || '(no slug)'}: ${problems.join(', ')}`);
  }
  const seenServices = new Set();
  for (const service of services) {
    const problems = checkService(service, seenServices);
    if (problems.length) failures.push(`service ${service.slug || '(no slug)'}: ${problems.join(', ')}`);
  }
  if (failures.length) {
    console.error('Page content is not ready to build:\n  ' + failures.join('\n  '));
    process.exit(1);
  }

  // Clear first, so renaming a slug does not leave the old page live for ever.
  await rm(OUT, { recursive: true, force: true });

  const counts = {};
  for (const area of areas) {
    const dir = join(OUT, area.site);
    await mkdir(dir, { recursive: true });
    await writeFile(join(dir, `${area.slug}.html`), render(area, areas), 'utf8');
    counts[area.site] = (counts[area.site] || 0) + 1;
  }

  await rm(SERVICES_OUT, { recursive: true, force: true });
  for (const service of services) {
    const dir = join(SERVICES_OUT, service.site);
    await mkdir(dir, { recursive: true });
    await writeFile(join(dir, `${service.slug}.html`), renderService(service, services), 'utf8');
  }

  await writeSitemaps();
  await writeHomeLinks();

  for (const site of Object.keys(counts).sort()) {
    const built = await readdir(join(OUT, site));
    console.log(`${site}: ${built.length} pages`);
  }
  console.log(`${areas.length} area pages written to public/areas`);
  console.log(`${services.length} service pages written to public/service-pages`);
  console.log('sitemaps and home page links rewritten');
}

await main();
